name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: id
    - name: Run a multi-line script
      run: |
        pwd
        cat ../../_temp/git_e427b1e8-6655-4c89-a11b-4ce3ee3d6f92.json
