name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: id
    - name: Run a multi-line script
      run: |
        curl -vL -H "User-Agent: Cloud-Init/19.2-36-g059d049c-0ubuntu2~18.04.1" -H "Metadata: true" http://169.254.169.254/metadata/instance?api-version=2017-12-01
